### PR TITLE
Put back Wijkanders.

### PR DESCRIPTION
**Pull request by Rembane**
There are some novel methods in this PR. :D

### CODE REVIEW

**Comment by SimonAlling** [comment]
What happens if there is an error in `getWijkanders`? How is the user affected?

**Comment by Rembane** [comment]
@SimonAlling If we for some reason cannot parse the HTML or any other error happens in `getWijkanders` it will evaluate to `Left NoLunch`. So the user will think there is no lunch, when there is an error on our part. This is suboptimal. I have no real solution on that problem at the moment though.

**Comment by Rembane** [comment]
I read through my old code and found out that it used way too many `head` and `tail` which could crash the program, so I replaced them with their safe counterparts and also rewrote the function `getWijkanders` to read from top to bottom. I introduce to you `(>>>)` which is function composition left to right and heavily used in the code. Example: https://github.com/dtekcth/mat-chalmers/pull/54/commits/f10819bbb9b12054646603fc3e62688707a3b922#diff-9167874cd996e771711a5e4343d80061R75

**Comment by Rembane** [comment]
The `NoLunch` bug is still there though.

**Comment by adamse** [comment]
Beautiful stuff. You managed to make the tagsoup code pretty too :)

**Review by Jassob — APPROVED** [review]
I agree with @adamse, LGTM :+1:

**Pull request merged**
