### PR TITLE
Serious Kåren graphql api refactoring

### PR DESCRIPTION
**Pull request by Rembane**
I did quite some changes to make future changes of the module that fetches stuff from Kårens GraphQL api easier. Some changes are reasonable, some are reckless. Gief feedback plx!

### CODE REVIEW

**Comment by adamse** [comment]
No?

**Comment by Jassob** [comment]
>
> No?
>
No, @Rembane got cold feet and decided that we should probably verify the
code some more.
FYI the new branch lives on dtekcth/mat-chalmers instead on Rembane's fork.

>

**Comment by Rembane** [comment]
I did indeed. I also remembered that the code might implement some changes that are not necessary anymore. So... more research needed.

**Comment by Rembane** [comment]
Okay, so Kårrestaurangen doesn't work anymore due to reasons... so... some of my changes might be useful then.

**Pull request closed without merging**
