### PR TITLE
Applied Brittany and hlint to the source code.

### PR DESCRIPTION
**Pull request by Rembane**
We now have a consistent style.

### CODE REVIEW

**Comment by adamse** [comment]
Maybe add hlint to the travis config: https://github.com/ndmitchell/hlint#running-with-continuous-integration

**Comment by adamse** [comment]
Needs imports of `fromMaybe` from `Data.Maybe` iirc.

**Comment by Rembane** [comment]
@adamse That is indeed true. Sometimes I commit and push without building, this is one of these cases.

**Comment by Rembane** [comment]
No, I didn't fix that, I just added comments so brittany would ignore the parts using Template Haskell.

You can read more about this here: https://github.com/lspitzner/brittany/issues/139

**Review by Jassob — CHANGES_REQUESTED** [review]
Put the changes introduced in edfbd245105df5679c75937809c0671756c8db47 and 6ead60a28327135080fe605cc8ef8db9a57dcf91 into the commits that they fix, then I'll approve! :+1:

I don't want to see any red crosses from failed checks, if commits fail, then fixup/squash or amend  them and force-push the new commits.

**Comment by Rembane** [comment]
@Jassob Done! I made one big commit instead of many small.

**Review by Jassob — APPROVED** [review]

**Pull request merged**
