### PR TITLE
Added logging to the fetching and parsing functions.

### PR DESCRIPTION
**Pull request by Rembane**
We implement logging to make it easier to use the data that caused an
error when debugging. We put the error together with the input data that
caused the error in the log file.

To do this I had to do code refactoring and feature implementations:

 - Added an option to the executable, to let the user set the filename
   of the logfile.
 - Rewrote all functions in the `Client` monad to mtl style.
 - Removed the `ClientT` monad transformer stack, it wasn't needed
   anymore when using mtl style.
 - Rewrote `getKaren` and `getKarenToday` to take a `ByteString` as
   argument and evaluate to `Either NoMenu [Menu]`
 - Added the `NMHttp` and `NMParseError` constructors to the `NoMenu`
   data type.
 - Almost all places that evaluated to `Maybe a` were changed to
   `Either NoMenu a` to allow for error messages to bubble up to
   the logger.
 - Added log files to .gitignore.

### CODE REVIEW

**Comment by Rembane** [comment]
**Q:** +220 -117 in one commit! What daftness has struck him?!

**A:** I tell you what daftness! I started hacking and followed the typchecker and made change after change and it resulted in this code. Now, I could go back and split it into many small commits that are atomic, well defined and so on, but it will take a lot of time and the result will be the same.

**Comment by Kirens** [comment]
Seems to work, had to update `shell.nix`

**Review by Kirens — APPROVED** [review]
LGTM

**Comment by Jassob** [comment]
> [...] Now, I could go back and split it into many small commits that are atomic, well defined and so on, but it will take a lot of time and the result will be the same.

I think it would be worth for the reviewers (which should be all of us) to actually has the small, well-defined and comprehensible units of code so that we could glimpse over the code and verify that it does not do anything unexpected. 

I understand that it takes some extra time to split a large commit into multiple (believe me, I seldom work in such a structured way that my commits @ einride shows), but that time is matched to the time we don't have to put to untangle a bunch of interconnected changes :)

**Comment by Jassob** [comment]
I actually waited to review this because I saw that there was a nice and structured 7 items long list that summarized the PR and I was expecting to see ~7 commits relating to each item in the list, but when I saw that there only was a single commit I realized that I'd probably need to invest more time than I had at time and postponed it until I had a free hour.

**Pull request merged**
