### PR TITLE
Try out Haskell CI (Github actions)

### PR DESCRIPTION
**Pull request by Jassob**
I don't understand anything about this Github Actions stuff. Where is the documentation I ask? Nobody knows, except maybe Github. I have not tried to contact their helpdesk.

### CODE REVIEW

**Comment by Jassob** [comment]
I am not sure whether we would actually gain anything from using Github actions rather than Travis. They seem to be comparable performance-wise (except that Travis can cache most of the time-intensive tasks, i.e. installing Stack and dependencies) and currently the documentation for Github actions is a bit spread out and difficult to navigate through. But I leave the PR open for us to discuss it.

**Comment by adamse** [comment]
is this a ci offering from github?

**Comment by Jassob** [comment]
> is this a ci offering from github?

Yes, apparently @dtekcth has signed up for the beta.

**Comment by adamse** [comment]
More CI is better CI :)?

**Review by adamse — APPROVED** [review]

**Pull request merged**
