### PR TITLE
Upgraded Stackage snapshot to LTS 13.25.

### PR DESCRIPTION
**Pull request by Rembane**
Upgraded the needed packages and removed thyme from extra dependencies
since it is included in this snapshot.

### CODE REVIEW

**Review by adamse — APPROVED** [review]

**Comment by Rembane** [comment]
hlint crashes in fun ways, I have no idea why. 

```
The command "curl -sL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -s ." exited with 1.
$ curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
Downloading and running hlint...
######################################################################## 100.0%
./app/Main.hs:36:61: Error: Parse error
Found:
    import           Network.HTTP.Client.TLS                  ( newTlsManager )
    import           Network.Wai.Middleware.RequestLogger     ( logStdout )
  > import           Network.Wai.Middleware.StaticEmbedded    ( static )
    import           System.Console.GetOpt                    ( ArgDescr(..)
                                                              , ArgOrder(..)
```

**Comment by Rembane** [comment]
...or is it weeder.

**Comment by Rembane** [comment]
Still no idea. :D

**Comment by Rembane** [comment]
@jassob fixed the error and submitted a PR that upgrades the project to even newer versions, therefore I close this PR.

**Pull request closed without merging**
