### PR TITLE
Drop Bootstrap CSS dependency

### PR DESCRIPTION
**Pull request by Jassob**
This commit removes the dependency of Bootstrap CSS, by reimplementing
the used rules from Bootstrap in our embedded stylesheet.

### CODE REVIEW

**Review by adamse — APPROVED** [review]
If it looks just as pretty go for it :)

**Review by Rembane — CHANGES_REQUESTED** [review]
I like the changes in the code, but I found a regression which I want you to fix before I can approve this PR. The site should look the same before and after application of this patch.

This is current mat.dtek.se:
mat dtek se

This is on the PR branch: 
pr-branch

**Comment by Jassob** [comment]
@Rembane, the issue is fixed! 

The core of the matter was that I looked at the current Bootstrap release (which is 4), but we used Bootstrap 3 and between those versions they actually changed the grid sizes.
Also added the correct Bootstrap link color.

**Comment by Jassob** [comment]
A quick remark, I'll squash all the commits together when the PR is approved for merge, so you don't need to look to much at the subsequent commit messages.

**Comment by Rembane** [comment]
This is much better. Thank you! 
Screenshot_2019-10-06 Lunch at Chalmers
Screenshot_2019-10-06 Lunch at Chalmers(1)

If you find out how to remove the scroll bar it would be amazing, but it's not needed.

**Review by Rembane — APPROVED** [review]

**Comment by Jassob** [comment]
@Rembane: What is pretty.js?

**Comment by Rembane** [comment]
> @Rembane: What is pretty.js?

It is a misspelling of prettier which is an opinionated code formatter that lives here: https://prettier.io/ it's pretty neat actually and lets me focus on code and not on formatting. I'll fix the typo in the commit and force push.

**Pull request merged**
