### PR TITLE
Special relativity (Updated Einstein)

### PR DESCRIPTION
**Pull request by Rembane**
**NB** don't merge this! Let @Rembane do it instead!

### CODE REVIEW

**Review by Jassob — COMMENTED** [review]
Ping @Rembane, is this RTM or not?

**Comment by Rembane** [comment]
@Jassob It's RTM, I messed things up in my head when I created the PRs. The code is alright though.

**Comment by Rembane** [comment]
The force push is to get the branch up to date with master.

**Comment by Rembane** [comment]
Remember to close #58 when this gets merged.

**Review by Jassob — APPROVED** [review]
Looks good to me, good to decouple the tag trimming stuff from wijkanders to make it usable in other modules as well.

**Comment by Jassob** [comment]
@Rembane You know that if you write "closes #58" in a commit message, the issue will automatically be closed when the commit is merged to master? 😁

**Comment by Rembane** [comment]
@Jassob I do, but I wanted to remember myself of this, since I forgot to write it in a commit message. :D

**Comment by Jassob** [comment]
@Rembane I think the same would work if you wrote the same line in the PR description and then merged the PR, but I'm not sure..

And now it's to late to try it out :(

**Comment by Rembane** [comment]
@Jassob There will be more PRs! :D

**Pull request merged**
